### ISSUE TITLE
QUESTION/REQ: custom functions

### ISSUE THREAD

**Issue by fmossott** [IBM/JSONata4Java#112]
I really appreciate this library and this language, however I would need to have more specific function for my specific scenarios.

It would be nice to add those custom functions without modifying the library.

I've found that it's currently possible to add additional functions with this code:

```
Expressions expr = Expressions.parse(jsonata);
final FrameEnvironment environment = expr.getEnvironment();
environment.setJsonataFunction(BasenameFunction.FUNCTION_NAME, new BasenameFunction());
environment.setJsonataFunction(DirnameFunction.FUNCTION_NAME, new DirnameFunction());
JsonNode val = expr.evaluate(jsonObj);
```

where BasenameFunction and DirnameFunction are classes implementing my custom functions.

Currently this is not documented and I'm scared that the methods I'm using to add custom functions, or to implement those functions may change in the future.

It would be nice if you can document and officially support a way to add custom functions.

Another possible problem could be the conflict between custom functions and future native functions, a possible solution is to reserve force custom functions to follow a name pattern (e.g. `$<prefix>-<function>`)

Thanks,
Franco

**Comment by wnm3** [comment]
I would be happy to have you contribute functions if desired. Let me know if you agree to the terms in  the agreements here and I'll add you as a developer. Otherwise, I don't believe there is any reason to change the registration mechanism so I think you are safe there. However, the functions should extend FunctionBase and implement Function to ensure the appropriate methods are available. In particular, there are some getMinArgs, getMaxArgs, and getSignature used to help assess when using the Context is allowed and to determine optional arguments. The function signature is defined as a pattern as defined here: https://docs.jsonata.org/programming#function-signatures. At present there are  no functions defined starting with X so I could see reserving function names with X_ prefix as you've suggested to ensure no collisions and advertising them as extensions. This would be a local agreement for JSONata4Java as I can't speak for Andrew Coleman and the large following  at jsonata.org.

I'm glad you are finding the library useful. I'm continuing to work on covering all the capabilities of jsonata.org but it is quite an extensive library. I'll have a new release soon that adds more compatibility for arrays, and possibly the lambda character function declarations.

**Comment by fmossott** [comment]
I agree that contributing to the open source would be the best option.
However in this case the custom functions that I need are strongly related to the product/context/scenario where I'm looking to use JSONata, so I was looking to add them in the consumer project.
I've already implemented some functions, and I was wondering how to reduce the risk to have to rewrite them due to changes in the next JSONata4Java releases.
I will use <myprefix>_<functionname> for the name, they should never conflict with JSONata functions that looks to use a camel case naming convention.

About the implementation, I was surprised to see that most of the function code is to implement validations, even if most can be extrapolated by the signature (I also see you have Signature class with a validate method, but currently this is not used)

Thanks,
Franco

**Comment by wnm3** [comment]
Yes, the Signature is not ready for use so I haven't fully implemented the logic.

I  believe you should use a letter and underscore since I believe these can be considered variables and they should begin with a letter. So rather than just underscore, if you would use X_ as the prefix I think we'll be in better compliance.
