### ISSUE TITLE
Function argument scope problem with map function

### ISSUE THREAD

**Issue by robertvanloenhout** [IBM/JSONata4Java#130]
I'm having an issue where the arguments of the function I call inside a map function doesn't seem to be properly scoped.
If the function has a parameter with the same name as the map function parameter, then I get unexpected results.

Example input:
```
[
  {
    "key1": "value1",
    "key2": "value2"
  }
]
```
JSONata:
```
(
  $value := function($v, $default) {
    $v = null  ? $default : $v
  };

  $map($, function($v, $i, $a) {
    $value($v.key1, "?") & "-" & $value($v.key2, "?")
  })
)
```
Expected result: "value1-value2". Actual result: "value1-"
Changing the $v name in the value or map function into something unique gives the expected result.

**Comment by wnm3** [comment]
What appears to be happening is, the first time $value is called $v is set to the object in the array (e.g., $map iterates over each array element). However, as a result of execution, when $value is called a second time, $v has been set to "value1" so attempting to resolve the path to .key for the string "value1" returns a null, and now with fixes, we get the default value "?" as the result of the comparison.

I'm trying to determine why $v changed from the object to the "value1" string in the environment's variable map. I suspect it may be the result of the first call but I need to debug this further. I wonder if I need to save the environment when executing the function and pop it when finished...

**Comment by wnm3** [comment]
I've added ExpressionVisitor.getNewEnvironment() that returns the old environment, and ExpressionVisitor.resetOldEnvironment() and added these in the DeclaredFunction invoke method. This ensured the second call to $value had the same environment as the first did (and any variables set within the function are only scoped to that function's environment. What was happening was $v was getting set for the variables to be passed into $value so it took on the "value1" and this remained for the 2nd call to $value.

I've fixed this in the code. You'll need to rebuild the jar file using mvn clean install until I push a new version to the Maven Central Repository. If you agree the problem is fixed, please close.

**Comment by robertvanloenhout** [comment]
I'm getting the expected result. Closing issue.
Thank you for fixing these issues so quickly!
