### ISSUE TITLE
NullPointerException when using dot operator with $contains

### ISSUE THREAD

**Issue by arm32x** [IBM/JSONata4Java#159]
When using the `.` operator in combination with the `$contains` function (and probably other functions, too), evaluating the expression throws a `NullPointerException`.

Here is some example code that reproduces the issue:
```java
ObjectMapper mapper = new ObjectMapper();
JsonNode input = mapper.readTree("{ \"a\": \"abc\", \"x\": \"xyz\" }");

Expressions parsed = Expressions.parse("a.$contains(\"ab\")");
JsonNode output = parsed.evaluate(input);

```

I am using version 1.5.8 of the library.

**Comment by wnm3** [comment]
This was just a bug. When using the context (e.g., with a value set before calling context so only one parameter is passed into the function contains) I neglected to lower the index used to retrieve the pattern. I checked a few other functions (e.g., each, filter) and they had the check for useContext ? 0:1 for the index. So, I hope this was a one off.

I've checked in the fix for the ContainsFunction.java and you can build a new jar using `mvn clean install` and the fix will be part of the next release.

Thanks for finding this bug.

**Comment by wnm3** [comment]
Please close once you've verified the fix worked. Thank you.

**Comment by arm32x** [comment]
It works. Thanks!
