### ISSUE TITLE
Array flattening not supported?

### ISSUE THREAD

**Issue by cdicsu** [IBM/JSONata4Java#18]
It looks like the descendant/multi-level wildcard (**.object) is either not functioning or isn't supported?  Another thing I noticed is that it looks like array flattening ($.arrayOfObjects) isn't supported.  Any plans for this in the future?  Thanks!

**Comment by wnm3** [comment]
I believe you are correct. Let me look into what is involved in supporting these features and get back to you soon. Thank you.

**Comment by wnm3** [comment]
I will have to look into wildcards later on, but I have begun added support for the $ context reference variable as follows (Note: there is an error when validationMessages is an array as I'm only processing the last entry...). I'll check in the work in progress and come back to debug the array issue later with hopes it can be fixed by Monday:
Attempting to load JSON from file: responses.json
Using json:
{
  "response" : {
    "addressLine1" : "1111 AVENUE O",
    "city" : "GALVESTON",
    "state" : "TX",
    "zip" : "77550",
    "zip4" : "8345",
    "validationMessages" : [ {
      "code" : "HR",
      "message" : "THE ADDRESS IS A HIGH RISE.",
      "severity" : "I"
    }, {
      "code" : "HR",
      "message" : "THE ADDRESS IS A HIGH RISE.",
      "severity" : "J"
    } ]
  },
  "conversationId" : "794c81c9-aad9-44d9-8add-6152b3174606",
  "transactionId" : "f115f062-ca77-45e0-a9e1-3a1ecefc38ca"
}
Enter jsonata expression (or q to quit):
$.response
{
  "addressLine1" : "1111 AVENUE O",
  "city" : "GALVESTON",
  "state" : "TX",
  "zip" : "77550",
  "zip4" : "8345",
  "validationMessages" : [ {
    "code" : "HR",
    "message" : "THE ADDRESS IS A HIGH RISE.",
    "severity" : "J"
  } ]
}
Enter jsonata expression (or q to quit):
$.response.validationMessages
{
  "code" : "HR",
  "message" : "THE ADDRESS IS A HIGH RISE.",
  "severity" : "J"
}
Enter jsonata expression (or q to quit):
$.response.validationMessages.severity
"J"
Enter jsonata expression (or q to quit):
$.x
** no match **
Enter jsonata expression (or q to quit):
q
Goodbye

**Comment by wnm3** [comment]
Fixed Array of Objects bug by iterating through the ExprOrSeqContext expressions (standard processing was only capturing the last element of the array in this circumstance):

Attempting to load JSON from file: responses.json
Using json:
{
  "response" : {
    "addressLine1" : "1111 AVENUE O",
    "city" : "GALVESTON",
    "state" : "TX",
    "zip" : "77550",
    "zip4" : "8345",
    "validationMessages" : [ {
      "code" : "HR",
      "message" : "THE ADDRESS IS A HIGH RISE.",
      "severity" : "I"
    }, {
      "code" : "HR",
      "message" : "THE ADDRESS IS A HIGH RISE.",
      "severity" : "J"
    } ]
  },
  "conversationId" : "794c81c9-aad9-44d9-8add-6152b3174606",
  "transactionId" : "f115f062-ca77-45e0-a9e1-3a1ecefc38ca"
}
Enter jsonata expression (or q to quit):
$.response
{
  "addressLine1" : "1111 AVENUE O",
  "city" : "GALVESTON",
  "state" : "TX",
  "zip" : "77550",
  "zip4" : "8345",
  "validationMessages" : [ {
    "code" : "HR",
    "message" : "THE ADDRESS IS A HIGH RISE.",
    "severity" : "I"
  }, {
    "code" : "HR",
    "message" : "THE ADDRESS IS A HIGH RISE.",
    "severity" : "J"
  } ]
}
Enter jsonata expression (or q to quit):
$.response.validationMessages
[ {
  "code" : "HR",
  "message" : "THE ADDRESS IS A HIGH RISE.",
  "severity" : "I"
}, {
  "code" : "HR",
  "message" : "THE ADDRESS IS A HIGH RISE.",
  "severity" : "J"
} ]
Enter jsonata expression (or q to quit):
$.response.validationMessages.severity
[ "I", "J" ]
Enter jsonata expression (or q to quit):
$.x
** no match **
Enter jsonata expression (or q to quit):
q
Goodbye

**Comment by wnm3** [comment]
I mistakenly checked in the fix for above on #17 the reference is 
[7400b57](https://github.com/IBM/JSONata4Java/commit/7400b5798ef8c03a6140b9a4c16aecd5e45000fe)

**Comment by wnm3** [comment]
I will create a new issue for "descendant/multi-level wildcard (**.object) is either not functioning or isn't supported" as that may take a bit more and I wanted to publish this new version 1.0.9 to Maven.

**Comment by cdicsu** [comment]
Thanks so much for your speedy resolution!  Much appreciated

**Comment by wnm3** [comment]
Since the topic was opened here, I thought I'd provide an update. I recently released version 1.1.12 that supports both wildcard reference types (*) and (**).
