### ISSUE TITLE
Expression does not evaluate correctly

### ISSUE THREAD

**Issue by atcol** [IBM/JSONata4Java#189]
Hello

I'm using this library via the Camel JSONata component and I believe there could be an issue with evaluation of `$merge(...)` and arrays in general.

Given this JSON payload:

<details>
  <summary>JSON Example</summary>

```json
[
  {
    "id": 19976,
    "buys": [
      {
        "listings": 1,
        "unit_price": 9837,
        "quantity": 186
      },
      {
        "listings": 1,
        "unit_price": 9836,
        "quantity": 16
      }
    ]
  },
  {
    "id": 19976,
    "buys": [
      {
        "listings": 1,
        "unit_price": 9837,
        "quantity": 186
      },
      {
        "listings": 1,
        "unit_price": 9836,
        "quantity": 16
      }
    ]
  }
]
```
</details>

and this JSONata expression:

```
$.$merge([{"t": $now()}, $])
```

I'd expect there to now be a new `t` field in each object in the array as in [this example](https://try.jsonata.org/SZOKq9I_0):

```json
[
  {
    "t": "2022-03-22T22:31:15.493Z",
    ...
  },
  {
    "t": "2022-03-22T22:31:15.493Z",
    ...
  }
]
```

**Comment by wnm3** [comment]
Hi, sorry, was on a vacation... I gather you found the latest version processed the result correctly since this was closed?

Attempting to load JSON from file: ./dataset32.json
Using json:
[ {
  "id" : 19976,
  "buys" : [ {
    "listings" : 1,
    "unit_price" : 9837,
    "quantity" : 186
  }, {
    "listings" : 1,
    "unit_price" : 9836,
    "quantity" : 16
  } ]
}, {
  "id" : 19976,
  "buys" : [ {
    "listings" : 1,
    "unit_price" : 9837,
    "quantity" : 186
  }, {
    "listings" : 1,
    "unit_price" : 9836,
    "quantity" : 16
  } ]
} ]
Enter jsonata expression (or q to quit):
$.$merge([{"t": $now()}, $])
[ {
  "t" : "2022-04-01T12:55:05.590Z",
  "id" : 19976,
  "buys" : [ {
    "listings" : 1,
    "unit_price" : 9837,
    "quantity" : 186
  }, {
    "listings" : 1,
    "unit_price" : 9836,
    "quantity" : 16
  } ]
}, {
  "t" : "2022-04-01T12:55:55.770Z",
  "id" : 19976,
  "buys" : [ {
    "listings" : 1,
    "unit_price" : 9837,
    "quantity" : 186
  }, {
    "listings" : 1,
    "unit_price" : 9836,
    "quantity" : 16
  } ]
} ]
Enter jsonata expression (or q to quit):

**Comment by atcol** [comment]
Hey, this issue itself wasn't closed - the one that referenced this in the Apache repo was instead (the UI here is confusing). 

I will see if I can update my version of JSONata4Java and see if the issue is resolved.

**Comment by atcol** [comment]
1.7.3 works for me - thanks!
