### ISSUE TITLE
Simple Tester UI

### ISSUE THREAD

**Issue by bluemel** [IBM/JSONata4Java#210]
Hi Nat...

this week I played around a little bit with Java Swing in order to create a small and simple "Tester UI" for JSONata4Java.
It is far from being as mighty as the original JSONata Exerciser UI but nevertheless I think it is much more pleasant to play around with JSONata4Java by means of this UI than the command line based Tester we have so far.

If you like to have a try:
- check out my new branch "tester-ui"
- build the project (mvn clean install)
- start the UI with ./testerui.sh (or testerui.cmd on Windows) and play around a little bit

If you like it I could polish it a bit and we could add it to the system instead or in addition to the command line based Tester.
Looking forward to your feedback to this tiny 280 LOC Java Swing hack.

BR
Martin

**Comment by bluemel** [comment]
Another nice feature that you could apply a transformation not only to JSON input but also to XML input. I simply applied Jackson's XmlMapper in order to get a JSON-Node to process.

**Comment by wnm3** [comment]
Thank you again. This is very nice. I have a few suggestions if you are open:

1. Rather than showing null for missing information, show ** no match ** as is done at https://try.jsonata.org/Z0MZ2NQrI
2. Rename to TesterUI.java or TesterUX.java or TryJSONata4Java.java (your choice). Since UI is an acronym it seems odd to see Ui...
3. Consider making the default test resource JSON and the test expression the same as the default at https://try.jsonata.org but allow a command line parameter to specify the JSON filename to be opened if supplied. This would make it more like the try.jsonata.org site.
4. Not important, but using white background for the JSON and expression and grey for the result would also seem more familiar to jsonata users...
5. Nice but not required, add a file picker to allow selection of files from the "new" testfiles directory... this has lots of other files that people have submitted for testing. Or, perhaps better, default to the src/test/resources where you've put some examples for testing (but add the original JSON file from try.jsonata.org there). I know people can just select all then paste in the JSON they want to test with so this really isn't required at all.

This is a really nice addition. Thanks again.

**Comment by bluemel** [comment]
1. and 2. are already implemented. For 3., 4. and 5. I need some more time.

Concerning the examples: I already took one of the test examples of the original JSONata Exerciser (try.jsonata.org) but instead of the "Invoice" example (which is the default example in the original JSONata Exerciser) I took the "Address" example because it generates a bit more output and it generates JSON output. I could also add a combo box like they have in the original JSONata Exerciser in order to switch between several examples but might restrict to the test examples that are currently working out well with JSONata4Java (Invoice, Address, Schema). Please note that the examples "Library" and "Bindings" are currently not working out in JSONata4Java.

By the way concerning "Bindings": I've not made any thought about the "Bindings" concept so far and would postpone this to a later point of time but might like to ask if JSONata4Java anyhow supports "Bindings" at all.

Concerning the background colors: of course we could make the whole look and feel a bit more similar to the original JSONata Exerciser. Maybe we could make the colors adjustable by the user and start with (white | white | grey) as the default. Fonts and font sizes might be also wished to be adjustable.

Concerning a file chooser: simply copy and paste some content like supported by the original JSONata Exerciser might be sufficient. Maybe what might I personally miss more in the original JSONata Exerciser is kind of app memory, so that the last "input" and "expression" you worked on is automatically present, when you start the UI again. This could be relatively easily implemented togheter with a memory of the colors and fonts.

**Comment by bluemel** [comment]
With a bit more work we have now a lot of possibilities: 
We can choose know between 3 JSONata Exerciser standard examples ("Invoice", "Address" and "Schema") and it's very easy to add more examples.
We can choose colors either from predefinded color schemas (also easily extendable) or even freely choos any color we like.
We can also tweak the Font used... and the UI alwas stores not only the UI settings but also the last status of your work.

**Comment by wnm3** [comment]
Sounds great -- look forward to merging your work.

**Comment by bluemel** [comment]
Pull request merged. New version 2.1.0 will provide the UI
