### ISSUE TITLE
$distinct on single value

### ISSUE THREAD

**Issue by pawelmaro** [IBM/JSONata4Java#236]
Probably in 2.2.4 $distinct on single value return array. 
If its intended change, maybe its ok.

**Comment by bluemel** [comment]
Yes... it's intended... and I confess I've changed it accordingly to the implementation of $sort ().
On the other hand, I'm not perfectly sure what is really correct there.

Anyway... my current plan is to rework  a l l  functions in JSONata4Java in order to work more uniform and also to have a behavior that is as close to original JSONata as possible.

25.11.2022 13:35:20 pawelmaro ***@***.***>:
