### ISSUE TITLE
Spaces & other characters in field names not parsed correctly

### ISSUE THREAD

**Issue by EvilMcJerkface** [IBM/JSONata4Java#25]
I might be doing something wrong, but spaces, hyphens, dollar signs, and possibly other interesting characters don't appear to be supported in field names.  For example, this test code snippet:

```
ObjectMapper mapper = new ObjectMapper();
String jsonString = "{\"MyField\": 3}";

try {
    JsonNode json = mapper.readTree(jsonString);
    PathExpression expression = PathExpression.parse("MyField");
    JsonNode result = expression.get(json, 0);
    assert (result != null);
    long myLong = result.longValue();
    assert (myLong == (long) 3);
}
catch (Exception e) {
    e.printStackTrace();
}
```

works fine.  But this throws a ParseException:

```
ObjectMapper mapper = new ObjectMapper();
String jsonString = "{\"My Field\": 3}";

try {
    JsonNode json = mapper.readTree(jsonString);
    PathExpression expression = PathExpression.parse("My Field");
    JsonNode result = expression.get(json, 0);
    assert (result != null);
    long myLong = result.longValue();
    assert (myLong == (long) 3);
}
catch (Exception e) {
    e.printStackTrace();
}
```

Adding quotes around the field name:

```
PathExpression expression = PathExpression.parse("\"My Field\"");
```

still throws a ParseException.  Same issue with hyphens, dollar signs, and probably other special characters.  Adding the context variable to a path like this, even without a special character in the field name, also throws a ParseException:

```
PathExpression expression = PathExpression.parse("$.MyField");
```

These special characters in field names all work fine (as long as they're quoted, of course) on [try.jsonata.org](http://try.jsonata.org).  Example using a space: http://try.jsonata.org/HytwpVUWL

Please let me know if this is just user error.  Thanks for your work on a usable Java-native JSONata!

Edit:  Using back-quotes to escape field names, as suggested by the ANTLR grammar, _does_ work without a parsing error, so this works OK:

```
PathExpression expression = PathExpression.parse("`My Field`");
```

But support for double-quotes ala the JavaScript JSONata would also be nice!

**Comment by wnm3** [comment]
This isn't your error. It is mine. I hadn't considered variables named like this. Let me look into this in more detail and see what I can do. Thanks for the detailed report.

**Comment by wnm3** [comment]
I am still looking into the issue. It is because an ID is defined as either:
           a letter followed by letters
or
           numbers or hyphens or underscores, or a backtick followed by anything (except a backtick) and closed with a backtick.
 
In your examples, using the backtick (under tilde on US keyboard) both `My Field` and $.`My Field` work as expected.
 
I need to determine whether adding double quotes to the definition breaks other things...
 
From the MappingExpression.g4 this is the definition:
ID    : [a-zA-Z] [a-zA-Z0-9_]*    | BACK_QUOTE ~[`]* BACK_QUOTE;
It does appear as though hyphen and underscore are also allowed in the non-quoted ID.
 
The documentation for JSONata only referenced using backticks if spaces were included in variable names:
https://docs.jsonata.org/simple
 
So I wonder if this is working as designed and you found a capability in jsonata.js that is the result of lenient coding. I'll ask on the slack channel. 
Best Regards, Nat
 
Nathaniel Mills
Senior Technical Staff Member
Phone: 1-860-812-5089 (m)
E-mail: wnm3@us.ibm.com
 
 
----- Original message -----From: Evil McJerkface <notifications@github.com>To: IBM/JSONata4Java <JSONata4Java@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [EXTERNAL] [IBM/JSONata4Java] Spaces & other characters in field names not parsed correctly (#25)Date: Wed, Jan 22, 2020 4:31 PM 
I might be doing something wrong, but spaces, hyphens, dollar signs, and possibly other interesting characters don't appear to be supported in field names. For example, this test code snippet:
ObjectMapper mapper = new ObjectMapper();String jsonString = "{\"MyField\": 3}";try {    JsonNode json = mapper.readTree(jsonString);    PathExpression expression = PathExpression.parse("MyField");    JsonNode result = expression.get(json, 0);    assert (result != null);    long myLong = result.longValue();    assert (myLong == (long) 3);}catch (Exception e) {    e.printStackTrace();}
works fine. But this throws a ParseException:
ObjectMapper mapper = new ObjectMapper();String jsonString = "{\"My Field\": 3}";try {    JsonNode json = mapper.readTree(jsonString);    PathExpression expression = PathExpression.parse("My Field");    JsonNode result = expression.get(json, 0);    assert (result != null);    long myLong = result.longValue();    assert (myLong == (long) 3);}catch (Exception e) {    e.printStackTrace();}
Adding quotes around the field name:
PathExpression expression = PathExpression.parse("\"My Field\"");
still throws a ParseException. Same issue with hyphens, dollar signs, and probably other special characters. Adding the context variable to a path like this, even without a special character in the field name, also throws a ParseException:
PathExpression expression = PathExpression.parse("$.MyField");
These special characters in field names all work fine (as long as they're quoted, of course) on try.jsonata.org. Example using a space: http://try.jsonata.org/HytwpVUWL
Please let me know if this is just user error. Thanks for your work on a usable Java-native JSONata!

**Comment by wnm3** [comment]
The reply I received on the jsonata.js slack channel seems to want to promote backticks over single and double quotes so I think I'll leave the code as is. Please close this issue if you agree. Thank you.

Early implementations used quotes, but it became quite unwieldy, so a decision was made to prefer backticks. I’m guessing they are not documented to discourage people from using them.

**Comment by EvilMcJerkface** [comment]
Sounds good to me - thanks for checking!
