### ISSUE TITLE
Arrays in multiple results are not merged

### ISSUE THREAD

**Issue by fmossott** [IBM/JSONata4Java#67]
While assessing this great library I've found a scenario that provides a result different form the try.jsonata.org one

Using this simple JSON
```
{
    "elem1": {
        "nums": [
            1,
            2
        ]
    },
    "elem2": {
        "nums": [
            3,
            4
        ]
    }
}
```

With these expressions:

`**.nums` or `*.nums`

I've the following results:

JSONata4Java (1.4.0): `[[1,2],[3,4]]`
https://try.jsonata.org/: `[1,2,3,4]` (this is what I was expecting)

**Comment by wnm3** [comment]
I am afraid you've caught me working through a bunch of unit tests for complete jsonata.js compatibility. I'd released v1.4.0 and today v1.4.1 that is mostly compatible, but has a glaring issue with array flattening. It has to do with how jsonata.js tracks steps during evaluation, and using Antlr for parsing, we don't have steps as a concept so the issue is creating the equivalent state for testing when to perform flattening. I'll be working on this next so hopefully will have something early next week.

**Comment by fmossott** [comment]
Thanks,
btw great work, it's very powerful while easy to use for simple scenarios.

Making further tests, I've found also this scenarios that work on try.jsonata.org and that are failing (also with 1.4.1) on JSONata4Java, they might be related to array flattening (let me know if you prefer I open independent issues)

`(*.nums)[0]+(*.nums)[-1]` fails because the two arguments of '+' are TextNode
while `elem1.nums[0]+elem2.nums[-1]` works correctly

`(*.nums)[0].$abs()` returns `[1,2]` instead of the expected `1`

`elem1.nums[0].$abs()` is failing because the context argument to abs is a TextNode

**Comment by wnm3** [comment]
I believe I was able to fix this problem. It was related to how the field_values was defined:
was '*' ('.' expr)? #field_values
but is now:  '*' #field_values

I also wasn't aware that jsonata.js could use the wildcard as a reference to an array (since it describes it as working with the fields of objects...).

I'm posting version 1.4.2 that should address your issues I believe.

**Comment by wnm3** [comment]
I've pushed the fix as version 1.4.2. Please check here in a couple of hours to retrieve it:
https://search.maven.org/search?q=g:com.ibm.jsonata4java 

If you agree your issue is fixed, please close this issue.

**Comment by fmossott** [comment]
The latest problems are fixed, thanks.

While the original array flattening issue is still present in version 1.4.2

**Comment by wnm3** [comment]
Thank you -- I've fixed for **.nums and it will be in 1.4.3 when that is released (soon). I've checked in the fix though.

**Comment by wnm3** [comment]
I've pushed version 1.4.3. You can check here for availability: https://search.maven.org/search?q=g:com.ibm.jsonata4java

**Comment by fmossott** [comment]
All my tests are working now.
Thanks a lot.
