### ISSUE TITLE
Support for regular expressions (regex)

### ISSUE THREAD

**Issue by wnm3** [IBM/JSONata4Java#71]
See https://docs.jsonata.org/regex

We do not parse for the regex delimiter /

**Comment by wnm3** [comment]
The RoundFunctionTest has some TODOs for regex recognition that currently reports as a parse error since we don't process regex using / characters.

**Comment by bluemel** [comment]
Hi Nat, I'm new to JSONata and JSONAata4Java. Does JSONAata4Java not support involving regular expressions into transformations at all or is there any workoround e. g. to test if a text from input data matches a regular expression using $contains(<input text>, /<regular expression>/)?

**Comment by wnm3** [comment]
Hi, you are correct, we don't support a RegEx expression in the ContainsFunciton:

			if (argPattern != null) {
				// Check to see if the pattern is just a string
				if (argPattern.isTextual()) {
					final String str = argString.textValue();
					final String pattern = argPattern.textValue();

					// Do a simple String::contains
					result = str.contains(pattern) ? BooleanNode.TRUE : BooleanNode.FALSE;
				} else {
					/*
					 * TODO: Add support for regex patterns once the grammar has been updated. For
					 * now, simply throw an exception.
					 */
					throw new EvaluateRuntimeException(ERR_ARG2BADTYPE);
				}
			} else {
				throw new EvaluateRuntimeException(ERR_ARG2BADTYPE);
			}
The issue is, ANTLR hasn't been set up to recognize the regular expression delimited with the slash (/) characters.

**Comment by wnm3** [comment]
You might be able to create a kludge solution by enclosing the expression in quotes as a string and testing for startsWith/endsWith "/" and then use the regular expression test but this isn't the best approach.

**Comment by bluemel** [comment]
OK Nat... a kludge solution is not what we aim for.

Is it very difficult to set up the Grammar for antlr to parse also strings framed with '/' instead of '"' in order to interpret them as regular expressions? Do we face any special parsing problems here or do we face other problems (e. g. that regular expressions in Javascript are fundamentally different to the Java regular expressions - at least simple expressions seemed to me to work quite as expected with the original JSONata Javascript implementation)?

**Comment by wnm3** [comment]
I'd be happy to add you as a contributor. If you can sign and forward the CLA from [here](https://github.com/IBM/JSONata4Java/blob/master/JSONata4Java_cla-individual.doc) and email it to me wnm3@us.ibm.com I will set you up.

**Comment by bluemel** [comment]
Hi Nat, I've come up with a first solution proposal for this issue.
Please have a short review on branch issue-71-support-regex. 

My first trail to solve this problem was to define REGEX as lexer rule in analgoy to STRING:
REGEX : '/' (ESC | ~[/\\])* '/'.
This failed because of the conflict with arithmetic expressions containing more than one DIV e. g.
24 / (2 + 2) / 3.
I've added some tests to class BasicExpressionsTest in order to ensure the arithmethic functionality.

This lead me to try it with some parser rules:
expr:
. . .
 | regularExpression                                      # regular_expression
. . .
 ;
regularExpression : '/' regexPattern '/';
regexPattern : ~DIV*;

This seems to work out. At least some first tests in ContainsFunctionTest run green.
If you like the implementation approach. We could go on supporting also /i (case insensitive) and /m (multi line) and also implement the regular expression evaluation for other functions that are supposed to support it e. g. $match().

**Comment by wnm3** [comment]
This sounds like a fine approach. I particularly liked how you'd identified the regularExpression so it becomes a class we can track and leverage in the functions that need it. Have you updated the function you originally wanted to use the regular expression? Let me know when you are ready and I'll pull and test and we can make a new release of JSONata4Java...

**Comment by bluemel** [comment]
I've updated / implemented regular expressions for the $contains() function so far. And I today pushed also a first approach for the /i (case insensitive) and the /m (multiline) variants of regular expressions. So on branch issue-71-support-regex we have some first tests for the $contains() function already running:
{ "$contains(\"abracadabra\", /.*bra.*/)", "true", null },
{ "$contains(\"abracadabra\", /bra/)", "true", null },
{ "$contains(\"abracadabra\", /[abcdr]*/)", "true", null },
{ "($compute := function($val1, $val2) { $val1 + $val2}; $contains($string($compute(120000 / 3 / 2, 10000)), /30+/))", "true", null },
{ "$contains(\"Hello World\", /wo/i)", "true", null },
However... we should tast a little bit more thoroughly before we make a new release.

Another question is if we should extend the solution before a new release and also tackle the 3 other JSONata functions that are supposed to work with regular expressions
* [$match()](https://docs.jsonata.org/string-functions#match)
* [$split()](https://docs.jsonata.org/string-functions#split)
* [$replace()](https://docs.jsonata.org/string-functions#rep

**Comment by wnm3** [comment]
Ideally we should include support for RegEx in the other functions that allow for it.

Thank you very much for your work on this. It should make others happy. It also may allow us to add additional unit tests back into the mix (that were commented out knowing we would fail them).

**Comment by bluemel** [comment]
I found a problem with the existing implementation: if a regular expression starts with '^' (which means either the begin of the input text or in multiline mode the begin of a line) the parser throws an error.

For example JSONata expression:
$contains("abracadabra", /^abracadabra$/)
is supposed to result in "true" (which it does in the JSONata exerciser) while it currently throws a parser error:
EvaluateException: line 1:26 at null: token recognition error at: '^'

It is not obvious for me at first glance what the problem is the grammer definition does not contain the circumflex accent character '^' at all so my first assumption is that it should be handled by the parser like any other arbitrary character.

Please have a short look at the ContainsFunctionTests (branch branch issue-71-support-regex) reproducing the problem in line 130
{ "$contains(\"abracadabra\", /^abracadabra$/)", "true", null },

**Comment by wnm3** [comment]
Sorry, I am on vacation until next Wed when I can look into this. Using the debugger might help identify what is happening. Good luck and thanks again for your work.

**Comment by bluemel** [comment]
Think I have solved the problem by defining a lexer rule
CIRCUMFLEX : '^';

I've also refined the parser rule for the regular expression pattern a bit in order to allow also escape sequence '\/':
regexPattern : (~DIV | '\\' DIV)*;

**Comment by bluemel** [comment]
Unfortunately the ^character is not the only one we have to define a lexer rule for. Same with character _ and probably a lot more we're currently not thinking of. Much worse is the fact that the lexer strips all whitespace characters from our regular expressions!

Here I see a serious problem for the whole idea to support JSONata's regular expression synax /<regex>/ with the current antlr parser implementation. Let's summarize our findings so far:

- if we let the lexer recognize the /<regex>/ in analogy to a STRING the lexer will mess up arithmetical expressions like: 
  ($guess + $n / $guess) / 2
  See: target\jsonata\jsonata-1.8.4\test\test-suite\groups\comments\case003.json
 
- if we let the parser recognize the /<regex>/ expression the lexer will mess up all regular expressions containing any whitespace e. g.
    $contains("abra   cadabra", /^abra *cadabra$/)
   See FunctionErrorTests on my branch

I'm quite unsure if it is possible to pass the whitespaces as tokens instead of stripping them and then let the parser deal with them. At least lthis would made the grammar very ugly.

Alternatives:
- the cludge solution "/ <regex> /": very ugly because incompatible to original JSONata
- always assume the given string to be a regular expression. In fact the current implementation of the $replace() function is already working like this because it uses Java String functions like replaceAll() that expect a regular expression (not exactly the JSONata behavior I assume)

At least we're getting nearer to the answer of my original question why JSONata4Java does not support the /<regex>/ syntax: it's not trivial and maybe impossible with the current ANTLR based paser implementation :-(. What do you think , Nat?

**Comment by bluemel** [comment]
I had a first try with the approach to pass a sequence of whitespace characters as token WS instead of skipping them.
The parser part of the grammar now contains also possible WS? between any other tokens.

I had partial success with this since my test FunctionErrorTests.replaceWithRegexWithBlank is now working out correctly.
On the other hand may test cases are failing now because they stumble now over one line in class ExpressionsVisitor:
Line 2269: valueNodes.add((ExprContext) valueField);
Here it seems that someone coded a class cast that is bound to fail since a TerminalNode is toally different to the ExprContext.

I checked if this line of code has been executed before and had to state that this line was "dead code" before my latest changes => it had probably never worked out.

You can find my latest changes now under new branch "issue-71-support-regex-alt1". I've opened a new branch for this approach since I'm still unsure if this approach is promising and we can cope with the problems it introduces.

**Comment by wnm3** [comment]
It might be reasonable to not allow actual space characters (e.g., 0x20) and instead only support the escaped space within the regex. There are several options: \x20 \040 or the /s, etc.

**Comment by wnm3** [comment]
The initial work on JSONata4Java was an internal requirement to support some JSON manipulations for simple rules and so was planned as a subset of jsonata.org features (you'll seem comments to this affect in the ExpressionsVisitor (around line 1018 for example). 

We've been working to expand coverage once it was open sourced, but as you've seen there are limitations due to the different parsing approach. It seems reasonable to either always treat the string as a regex expression, or to have some limitations on the implementation (provided we can articulate them in the README.md so others would know the differences from jsonata.org.

**Comment by bluemel** [comment]
Good idea Nat, \s \x40 and \s all work out in my tests.

So we could maybe live with the restriction that people have to use \s for the /regular expression/.
Since $contains and $replace are now working out on my "branch issue-71-support-regex" (with the know restriction) I could continue with $split and $match.

Before I continue maybe you could give me a short opinion about my experiments with branch "branch issue-71-support-regex-alt1" where I tried not to skip whitespace characters by the lexer and handle them with the parser. My personal feeling is that this could complicate the parser too much and it might be hard to solve the current problems with according adaption to the parser implementation. If you have the same meaning I would remove this experimental branch and continiue with the approach that is much less invasive concerning parser changes.

**Comment by wnm3** [comment]
I can't tell you the number of days lost trying to tweak the parser only to revert back to where I started. It is a finicky bitch. I think having added regex support is a huge step forward and having the small limitations to have to be explicit with the escaped spaces is a reasonable compromise. I'd recommend dropping the branch trying to account for allowing spaces and finish updating the regex on the prior branch. Then we can publish a new release based on your work.

**Comment by bluemel** [comment]
Ok Nat, I've implemented also the $split and the $match function to work with the /regex/ arguments.
So I think we're getting now near to a releasable solution.

$contains(), $match(), $split(), and $replace() work now with the /regex/ arguments.
We just have to confess to our useres the "\s" hack in our documentation.

However:
Functions $match, $replace, $split have always used (and still use) Java implementations that in every case try to evaluate a regular expression. That means an argument 'regex' or 'regex' has always treated like now /regex/ by these functions besides that whitespaces are handeled differently. Functions contains is the only one that until now did not support regular expressions at all and now does it a little bit more correctly than the other 3 functions since arguments nested in '' or "" are never handeled as regular expression. We have now 3 possibilities:

1) Leave things as they are and live with this asymetry. Advantages: 1) no breaking change, 2) no work to be done anymore.
   Disadvantage beside the asymmtry: 3 Functions will continue to behave differently to the original JSONata implementation in the sense that they also evaluate simple string arguments as regular expression.
 
2) Change the contains function always to match a regular expression. Advantage: all 4 functions show the same behaviour concerning regulag expressions, Advantage: symmetric behavior of all 4 functions, not much implementation work. Disadvantages: breaking change $contains() expressions could break because of arguments accidentally evaluated as regular expressions now.

3) Change the 3 functions not to evaluate regular expressions anymore for normal string arguments. Advantages  symmetric behavior of all 4 functions, Behaviour of all 4 functions is closest to the JSONata original. Disadvantages: breaking change, expressions using these functions could have relied on the regex evaluation (I dont know if this is currently a documented feature), a bit of implementation work to do.

My favorite is solution 3 but I could also live with 1 or 2. What do you think Nat?

**Comment by bluemel** [comment]
I found even more argument to strive for solution 3 and to have a closer look at the current implementations of $match(), $split() and $replace():

- Using the as is implementation for $match(), $split() and $replace() does currently not yet support the /regex/i and /regex/m notation yet.

- The current $match() implementation has a problem to support the groups correctly:
  $match('xxabbbxx', /(a+)(b+)/) delivers one group "ab" in original JSONata we have two correct groups "a" and "bbb".
  In JSONata4Java we have a correct implementation for non-regular expresion ($match('xxabbbxx', 'ab')) which is not provided by original JSONata at all (I do not see a problem to continue to support this additional alternative in JSONata4Java for downward compatibility reasons)

**Comment by wnm3** [comment]
Sorry Martin, my email was down until now... I agree with solution 3 approach. We should simply update the README.md file to explain what changed and to identify the use of the escape \s for spaces.

**Comment by bluemel** [comment]
OK Nat, see my pull request https://github.com/IBM/JSONata4Java/pull/206.
The solution should be fairly complete now.

**Comment by bluemel** [comment]
Think this issue and also issue https://github.com/IBM/JSONata4Java/issues?q=regular can be closed now.

**Comment by bluemel** [comment]
Hi Nat,one thing comes to my mind: I've neither found nor figured out a sensible test to verify "multiline" regular expressions so far. All I can say is that these expressions /pattern/m are implemented in analogy to "case insensitive" regular expressions /pattern/i - case insensitive regular expressions are already tested successfully.The hope is that a multiline regular expression in Java has the same semantics and works the same way than in original JSONata. But it would be better to have a test.BRMartinAm 21.09.22, 17:16 schrieb Nathaniel Mills ***@***.***>:

   
  Closed #71 as completed.
